version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 15
    target-branch: 3.x-develop
    reviewers:
    - pandaskii
 - package-ecosystem: npm
    directory: "/cy"
    schedule:
      interval: daily
    target-branch: 3.x-develop
