---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: |
      docker compose up -d "$@"

  down:
    usage: Delete project.
    cmd: docker compose down

  build:
    usage: Build project.
    cmd: |
      docker compose build "$@"

  restart:
    usage: Restart Docker containers.
    cmd: docker compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker compose stop "$@"

  watch:
    usage: Use Compose Watch for live development.
    cmd: docker compose watch

  cli:
    usage: Start a shell.
    cmd: docker compose exec govcms bash

  composer:
    usage: Start a composer command.
    cmd: docker compose exec govcms composer "$@"

  rector:
    usage: Analyze your code with Rector and review suggested changes.
    cmd: docker compose exec govcms rector "$@"

  phpunit:
    usage: Run PHPUnit tests.
    cmd: docker compose exec govcms phpunit "$@"

  drupal-check:
    usage: Static analysis tool to check for correctness and deprecation errors.
    cmd: docker compose exec govcms drupal-check "$@"

  cypress:
    usage: Run all Cypress tests
    cmd: |
      cd cy
      export CYPRESS_BASE_URL=http://localhost:8888
      npx cypress run "cypress/e2e/*" --env drupalDrushCmdLine="docker compose exec govcms drush %command"

  cr:
    usage: Alias for 'cypress'
    cmd: |
      ahoy cypress

  co:
    usage: Open a new Cypress testing window
    cmd: |
      cd cy
      export CYPRESS_BASE_URL=http://localhost:8888
      npx cypress open --env drupalDrushCmdLine="docker compose exec govcms drush %command"
