name: govcms-tests
recipe: drupal10
services:
  appserver:
    api: 3
    type: lando
    app_mount: false
    services:
      image: govcmstesting/govcms:latest
      command: docker-php-entrypoint apache2-foreground
      ports:
        - '80'
        - '443'
    run:
      - rm -rf /var/www/html
      - ln -sf /app/web /var/www/html
    run_as_root:
      - chown -R www-data:www-data /app/web/sites