services:
  ##########################################
  # tests: The tests used by local
  ##########################################
  tests:
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    image: govcms.ops/tests
    develop:
      watch:
        - action: sync
          path: .
          target: /tests
          ignore:
            - vendor/
            - node_modules/
        - action: rebuild
          path: composer.json
  
  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms
    image: govcms.ops/govcms
    depends_on:
      - tests
      - mariadb
    ports:
      - "8888:80"
    volumes:
      - $PWD/app/modules:/app/web/modules/develop
      - $PWD/app/themes:/app/web/themes/develop
      - /var/www/html/sites
      - $PWD/behat:/app/tests/behat
      - $PWD/cy:/app/tests/cy
      - $PWD/phpunit:/app/tests/phpunit
    develop:
      watch:
        - action: sync
          path: .
          target: /app/tests
          ignore:
            - vendor/
            - node_modules/

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - /var/lib/mysql

networks:
  default:
    external: false