services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5001:5000"
    volumes:
      - ./data/registry:/var/lib/registry
      - ./data/registry/config.yml:/etc/docker/registry/config.yml

volumes:
  registry:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/registry