services:
  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: .docker/Dockerfile.govcms
    container_name: govcms
    volumes:
      # Source code volumes
      - modules:/app/web/modules/develop
      - themes:/app/web/themes/develop
      - /var/www/html

      # Test volumes
      - behat:/app/tests/behat
      - cy:/app/tests/cy
      - phpunit:/app/tests/phpunit

      # Composer cache volume
      - composer_cache:/home/govcms/.cache

      # Configuration files
      - ./.docker/config/rector.php:/app/rector.php
    environment:
      - GOVCMS_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.govcms.rule=Host(`govcms.localhost`)"
      - "traefik.http.routers.govcms-http.entrypoints=web"
      - "traefik.http.services.govcms.loadbalancer.server.port=80"
    networks:
      - internal
      - govcms-local-services_web
      - govcms-local-services_internal
    develop:
      watch:
        - action: sync
          path: .
          target: /app/tests
          ignore:
            - vendor/
            - node_modules/
            - app/
            - data/
        - action: rebuild
          path: composer.json

  ##########################################
  # cypress: Cypress testing service
  ##########################################
  cypress:
    image: cypress/included
    container_name: cypress
    volumes:
      - ./cy:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - internal
    environment:
      - CYPRESS_baseUrl=http://govcms
    entrypoint: ["npx", "cypress", "run", "--project", "/e2e", "--spec", "/e2e/cypress/e2e/4-ui/*.cy.js"]

volumes:
  modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/modules
  themes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/themes
  drupal_sites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/drupal_sites
  behat:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./behat
  cy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cy
  phpunit:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./phpunit
  composer_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/composer

networks:
  internal:
    external: false
  govcms-local-services_web:
    external: true
  govcms-local-services_internal:
    external: true