services:
  ##########################################
  # tests: The GovCMS local tests
  ##########################################
  tests:
     build:
      context: .
      dockerfile: $PWD/Dockerfile
     image: govcmstesting/tests

  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms
    image: govcmstesting/govcms
    depends_on:
      - tests
      - mariadb
    ports:
      - "8888:80"
    volumes:
      - $PWD/app/modules:/app/web/modules/develop
      - $PWD/app/themes:/app/web/themes/develop
      - /var/www/html/sites

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - $PWD/app/database:/var/lib/mysql

networks:
  default:
    external: false