name: GovCMS CI Tests

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest

    container:
      image: govcmstesting/php:8.1-apache
      
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_DATABASE: govcms
          MYSQL_ROOT_PASSWORD: govcms
          MYSQL_ROOT_HOST: "%" 
                    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'govcms/govcms'
        ref: '3.x-develop'
        path: 'app'

    - name: Cache Composer packages
      id: composer-cache-govcms
      run: |
        cd app
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
  
    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache-govcms.outputs.dir }}
        key: ${{ runner.os }}-php-govcms-${{ hashFiles('app/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-govcms-

    - name: Install GovCMS dependencies
      run: |
       cd app
       composer update --profile --prefer-dist --optimize-autoloader

    - name: Setup webserver
      run: |
       rm -rf /var/www/html
       ln -sf $GITHUB_WORKSPACE/app/web /var/www/html
       service apache2 restart

    - name: Install GovCMS site
      run: |
       cd app
       ./bin/drush site-install -y govcms --db-url=mysql://root:govcms@mariadb:3306/govcms --site-name='GovCMS' --account-pass=password install_configure_form.enable_update_status_emails=NULL install_configure_form.enable_update_status_module=NULL || true
       chown -R www-data:www-data web/sites

    - uses: actions/checkout@v4
      with:
        path: 'app/tests'

    - name: Install dependencies
      run: |
        cd app/tests/cy && npm ci

    - name: Run Cypress tests
      run: |
        export PATH=$PATH:/app/tests/vendor/bin:/app/vendor/bin
        cd app/tests/cy && npx cypress run --config baseUrl=http://localhost/
