name: GovCMS CI Tests

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest

    container:
      image: govcmstesting/ci:8.2-apache
      
    services:
      mariadb:
        image: mariadb:lts
        env:
          MYSQL_DATABASE: govcms
          MYSQL_ROOT_PASSWORD: govcms
          MYSQL_ROOT_HOST: "%" 
                    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'govcms/govcms'
        ref: '3.x-develop'
        path: '.'

    - name: Install GovCMS dependencies
      run: |
       composer update --profile --prefer-dist --optimize-autoloader

    - name: Setup webserver
      run: |
       rm -rf /var/www/html
       ln -sf $GITHUB_WORKSPACE/web /var/www/html
       service apache2 restart

    - name: Install GovCMS site
      run: |
       bin/drush site-install -y govcms --db-url=mysql://root:govcms@mariadb:3306/govcms --site-name='GovCMS' --account-pass=password install_configure_form.enable_update_status_emails=NULL install_configure_form.enable_update_status_module=NULL || true
       chown -R www-data:www-data web/sites

    - uses: actions/checkout@v4
      with:
        path: 'tests'

    - name: Install dependencies
      run: |
        cd tests/cy && npm ci

    - name: Run Cypress tests
      run: |
        cd tests/cy && npx cypress run --config baseUrl=http://localhost --env drupalDrushCmdLine="$GITHUB_WORKSPACE/bin/drush --root=/var/www/html %command"
